### ISSUE TITLE
NPM package lacks dist

### ISSUE THREAD

**Issue by earksiinni** [nerdmax/html-webpack-change-assets-extension-plugin#13]
Hi there, thanks for your hard work :-).

Could you please generate the `dist` files and upload a package to NPM? The package doesn't work out of the box, it has to be built.

**Comment by bradwestfall** [comment]
Yep, I get `Cannot find module 'html-webpack-change-assets-extension-plugin'`

**Comment by nerdmax** [comment]
@earksiinni Thanks for leaving comments. I've already published this library to npm since the beginning. You can use `npm install --save-dev html-webpack-change-assets-extension-plugin` to install this library and use `cosnt HtmlWebpackChangeAssetsExtensionPlugin = require('html-webpack-change-assets-extension-plugin')` to inject this library. Please check the readme file for more details. 

PS: If you want to add or modify this library. I suggest to play with it in test/html-webpack-change-assets-extension-plugin.test.ts file. You can run `npm run test` to run this file.

**Comment by nerdmax** [comment]
> Yep, I get `Cannot find module 'html-webpack-change-assets-extension-plugin'`

Could you please give me more information about this error? Like how you use it or where you want to use it?

**Comment by nerdmax** [comment]
I just published a new version which will resolve this issue. Apology for any inconvenience. @earksiinni, @bradwestfall Thank you again for addressing this issue.
